version: '3.9'

services:
  order-service:
    container_name: order-server
    build: 
      context: ./services/order
      dockerfile: ./Dockerfile
    ports:
      - "8181:8181"
  payment-service:
    container_name: payment-server
    build:
      context: ./services/payment
      dockerfile: ./Dockerfile
    ports:
      - "8282:8282"
  product-service:
    container_name: product-server
    build:
      context: ./services/product
      dockerfile: ./Dockerfile
    ports:
      - "8383:8383"
  promo-service:
    container_name: promo-server
    build:
      context: ./services/promo
      dockerfile: ./Dockerfile
    ports:
      - "8484:8484"