services:
  gateway:
    container_name: anemone-api-gateway
    image: nginx:latest
    volumes:
      - "./gateway/nginx/sites/:/etc/nginx/conf.d"
    ports:
      - "80:80"
    networks:
      - gateway
  order-service:
    container_name: order-server
    build: 
      context: ./services/order
      dockerfile: ./Dockerfile
    ports:
      - "8181:8181"
    networks:
      - gateway
  payment-service:
    container_name: payment-server
    build:
      context: ./services/payment
      dockerfile: ./Dockerfile
    ports:
      - "8282:8282"
    networks:
      - gateway
  product-service:
    container_name: product-server
    build:
      context: ./services/product
      dockerfile: ./Dockerfile
    ports:
      - "8383:8383"
    networks:
      - gateway
  promo-service:
    container_name: promo-server
    build:
      context: ./services/promo
      dockerfile: ./Dockerfile
    ports:
      - "8484:8484"
    networks:
      - gateway

networks:
  gateway: {}