services:
  db-postgres:
    container_name: anemone-postgres
    image: postgres:17
    volumes:
      - ./database/postgresql/pgdata:/var/lib/postgresql
      - ./database/postgresql/create-multiple-db.sh:/docker-entrypoint-initdb.d/create-multiple-db.sh
    environment:
      POSTGRES_MULTIPLE_DATABASES: anemone_order, anemone_product, anemone_promo
      POSTGRES_USER: anemone
      POSTGRES_PASSWORD: anemone
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anemone"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - anemone-network
  gateway:
    container_name: anemone-api-gateway
    image: nginx:latest
    volumes:
      - "./gateway/nginx/www/:/var/www"
      - "./gateway/nginx/sites/:/etc/nginx/conf.d"
    ports:
      - "80:80"
    networks:
      - anemone-network
    depends_on:
      - order-service
      - payment-service
      - product-service
      - promo-service
  order-service:
    container_name: anemone-order-server
    build: 
      context: ./services/order
      dockerfile: ./Dockerfile
    ports:
      - "8181:8181"
    networks:
      - anemone-network
    depends_on:
      - db-postgres
  payment-service:
    container_name: anemone-payment-server
    build:
      context: ./services/payment
      dockerfile: ./Dockerfile
    ports:
      - "8282:8282"
    networks:
      - anemone-network
    depends_on:
      - db-postgres
  product-service:
    container_name: anemone-product-server
    build:
      context: ./services/product
      dockerfile: ./Dockerfile
    ports:
      - "8383:8383"
    networks:
      - anemone-network
    depends_on:
      - db-postgres
  promo-service:
    container_name: anemone-promo-server
    build:
      context: ./services/promo
      dockerfile: ./Dockerfile
    ports:
      - "8484:8484"
    networks:
      - anemone-network
    depends_on:
      - db-postgres
  db-migrations:
    container_name: anemone-db-migrations
    image: migrate/migrate
    depends_on:
      db-postgres:
        condition: service_healthy
    volumes:
      - ./services/product/db/migrations:/product-migrations
      - ./services/promo/db/migrations:/promo-migrations
      - ./services/order/db/migrations:/order-migrations
    entrypoint: >
      sh -c "
        migrate -path product-migrations -database 'postgres://anemone:anemone@db-postgres:5432/anemone_product?sslmode=disable' up &&
        migrate -path promo-migrations -database 'postgres://anemone:anemone@db-postgres:5432/anemone_promo?sslmode=disable' up &&
        migrate -path order-migrations -database 'postgres://anemone:anemone@db-postgres:5432/anemone_order?sslmode=disable' up
      "
    networks:
      anemone-network:

networks:
  anemone-network: {}
